/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DayEntry = IDL.Record({
  'rr' : IDL.Float64,
  'eurusdPct' : IDL.Float64,
  'gbpjpyPct' : IDL.Float64,
  'source' : IDL.Text,
  'gbpusdPct' : IDL.Float64,
  'date' : IDL.Text,
  'trades' : IDL.Nat,
  'note' : IDL.Text,
  'pnlPct' : IDL.Float64,
  'asiaPct' : IDL.Float64,
  'us30Pct' : IDL.Float64,
  'usdjpyPct' : IDL.Float64,
  'audusdPct' : IDL.Float64,
  'nyPct' : IDL.Float64,
  'psych' : IDL.Nat,
  'xauusdPct' : IDL.Float64,
  'londonPct' : IDL.Float64,
  'commissions' : IDL.Float64,
  'riskPct' : IDL.Float64,
  'slippage' : IDL.Float64,
});
export const UserSettings = IDL.Record({
  'oandaAccountId' : IDL.Text,
  'dailyGoal' : IDL.Float64,
  'oandaApiKey' : IDL.Text,
  'trackedPairs' : IDL.Vec(IDL.Text),
  'ddLimit' : IDL.Float64,
  'oandaEnv' : IDL.Text,
  'weeklyGoal' : IDL.Float64,
  'lastSync' : IDL.Int,
});

export const idlService = IDL.Service({
  'addOrUpdateDayEntry' : IDL.Func([DayEntry], [], []),
  'deleteDayEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllDayEntries' : IDL.Func([], [IDL.Vec(DayEntry)], ['query']),
  'getDayEntry' : IDL.Func([IDL.Text], [DayEntry], ['query']),
  'getSettings' : IDL.Func([], [UserSettings], ['query']),
  'saveSettings' : IDL.Func([UserSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DayEntry = IDL.Record({
    'rr' : IDL.Float64,
    'eurusdPct' : IDL.Float64,
    'gbpjpyPct' : IDL.Float64,
    'source' : IDL.Text,
    'gbpusdPct' : IDL.Float64,
    'date' : IDL.Text,
    'trades' : IDL.Nat,
    'note' : IDL.Text,
    'pnlPct' : IDL.Float64,
    'asiaPct' : IDL.Float64,
    'us30Pct' : IDL.Float64,
    'usdjpyPct' : IDL.Float64,
    'audusdPct' : IDL.Float64,
    'nyPct' : IDL.Float64,
    'psych' : IDL.Nat,
    'xauusdPct' : IDL.Float64,
    'londonPct' : IDL.Float64,
    'commissions' : IDL.Float64,
    'riskPct' : IDL.Float64,
    'slippage' : IDL.Float64,
  });
  const UserSettings = IDL.Record({
    'oandaAccountId' : IDL.Text,
    'dailyGoal' : IDL.Float64,
    'oandaApiKey' : IDL.Text,
    'trackedPairs' : IDL.Vec(IDL.Text),
    'ddLimit' : IDL.Float64,
    'oandaEnv' : IDL.Text,
    'weeklyGoal' : IDL.Float64,
    'lastSync' : IDL.Int,
  });
  
  return IDL.Service({
    'addOrUpdateDayEntry' : IDL.Func([DayEntry], [], []),
    'deleteDayEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllDayEntries' : IDL.Func([], [IDL.Vec(DayEntry)], ['query']),
    'getDayEntry' : IDL.Func([IDL.Text], [DayEntry], ['query']),
    'getSettings' : IDL.Func([], [UserSettings], ['query']),
    'saveSettings' : IDL.Func([UserSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };