/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DayEntry {
  'rr' : number,
  'eurusdPct' : number,
  'gbpjpyPct' : number,
  'source' : string,
  'gbpusdPct' : number,
  'date' : string,
  'trades' : bigint,
  'note' : string,
  'pnlPct' : number,
  'asiaPct' : number,
  'us30Pct' : number,
  'usdjpyPct' : number,
  'nyPct' : number,
  'psych' : bigint,
  'xauusdPct' : number,
  'londonPct' : number,
  'commissions' : number,
  'riskPct' : number,
  'slippage' : number,
}
export interface UserSettings {
  'oandaAccountId' : string,
  'dailyGoal' : number,
  'oandaApiKey' : string,
  'trackedPairs' : Array<string>,
  'ddLimit' : number,
  'oandaEnv' : string,
  'weeklyGoal' : number,
  'lastSync' : bigint,
}
export interface _SERVICE {
  'addOrUpdateDayEntry' : ActorMethod<[DayEntry], undefined>,
  'deleteDayEntry' : ActorMethod<[string], boolean>,
  'getAllDayEntries' : ActorMethod<[], Array<DayEntry>>,
  'getDayEntry' : ActorMethod<[string], DayEntry>,
  'getSettings' : ActorMethod<[], UserSettings>,
  'saveSettings' : ActorMethod<[UserSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];